{% set name = "polygon-api-client" %}
{% set version = "1.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 15f02ca8108340b4aa7ef5ad7bfd937bb464198bd0201b7e8027aa65cd75bc29

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  script_env:
    - VERSION={{ version }}
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - poetry
  run:
    - python >=3.8
    - certifi >=2022.5.18
    - setuptools
    - urllib3 >=1.26.9
    - websockets >=10.3

test:
  imports:
    - polygon

about:
  home: https://github.com/polygon-io/client-python
  summary: Polygon API client
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - timkpaine
    - yehoshuadimarsky
